jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  # HS512 알고리즘으로 수행할 것이기에 키 길이 64바이트로 해야함
  expiry-seconds: 60

spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:file:./database/spring-security;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;"
    username: sa
    password:
    driver-class-name: "org.h2.Driver"
  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      encoding: UTF-8
      mode: never

  application:
    name: spring security 01
#  thymeleaf:
#    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  jpa:
    hibernate:
      ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          kakao:
            client-name: kakao
            client-id: 80b063bff8c23a47b2e3674ab70fb32d
            client-secret: d5CRqH5irf65GrLFsvnDNsPSaN3PqHbk
            scope: profile_nickname, profile_image
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST

#  ssl:
#    enabled: true
#    key-alias: prgrms_keystore
#    key-store: classpath:prgrms_keystore.p12
#    key-store-password: prgrms123
#    key-password: prgrms123
#    trust-store: classpath:prgrms_truststore.p12
#    trust-store-password: prgrms123
