jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  # HS512 알고리즘으로 수행할 것이기에 키 길이 64바이트로 해야함
  expiry-seconds: 60

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:file:./database/spring-security;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;"
    username: sa
    password:
    driver-class-name: "org.h2.Driver"
  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      encoding: UTF-8
      mode: always

  application:
    name: spring security 01
#  thymeleaf:
#    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  jpa:
    hibernate:
      ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

#  ssl:
#    enabled: true
#    key-alias: prgrms_keystore
#    key-store: classpath:prgrms_keystore.p12
#    key-store-password: prgrms123
#    key-password: prgrms123
#    trust-store: classpath:prgrms_truststore.p12
#    trust-store-password: prgrms123
